### PR TITLE
update license to Apache 2.0

### PR DESCRIPTION
**Pull request by eirinikos**
This commit replaces the MIT license with the Apache 2.0 license.

(All CNCF projects should use the Apache License 2.0 - please see opentracing/specification#61 for context.)

**Note:**
- The copyright reference to OT is as such: `Copyright The OpenTracing Authors`

**Question:**
- I left these 3rd-party and **mocktracer** files as-is for now. Could someone advise on whether they need to be updated in any way?
```
/3rd_party/include/opentracing/catch2/catch.hpp
/3rd_party/include/opentracing/catch2/LICENSE.txt
/3rd_party/include/opentracing/expected/expected.hpp
/3rd_party/include/opentracing/expected/LICENSE
/3rd_party/include/opentracing/variant/LICENSE
/3rd_party/include/opentracing/variant/recursive_wrapper.hpp
/mocktracer/LICENSE.apache
/mocktracer/src/base64.cpp
```

We would like to give previous contributors a 7-day period to air any objections. If you have any concerns or feedback, please notify us by April 4th.  Thanks!

(CC @dankohn @bhs)
(CC previous contributors: @rnburn @lookfwd @isaachier @heyleke @pantoss @Shruti9520 @PikBot @hennna @jmillikin-stripe @stgarf @SaintDubious)

### CODE REVIEW

**Comment by rnburn** [comment]
I'm fine with using apache.

Those other bits you pointed to were taken from other project, so I image we'd need to keep the licenses?

**Comment by dankohn** [comment]
@eirinikos Nothing in the `/3rd_party/` directory should be changed. CNCF's license policy is for the main repo, not for dependent libraries (though we separately scan and review those).

**Comment by eirinikos** [comment]
Thanks @rnburn & @dankohn. I'll leave everything in the `3rd_party` and `mocktracer` files as-is, and we'll let this PR sit for a few more days before merging. 👍

**Comment by rnburn** [comment]
@eirinikos - can we merge this?

**Comment by eirinikos** [comment]
@rnburn yup, this is ready to be merged!

**Pull request merged**
